name: megatron_t5
restore_from_path: null # used when starting from a .nemo file

#TODO: mode optim overrides to some other file
model:
  optim:
    lr: 0.0001
    betas:
      - 0.9
      - 0.999
    eps: 1e-8